Models/Demo01ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Is3106Lecture12DotNet.Models
{
    public class Demo01ViewModel
    {
        public int RequestScopedCounter { get; set; }
        public int SessionScopedCounter { get; set; }
        public string SessionScopedString { get; set; }
        public Book SessionScopedObject { get; set; }



        public Demo01ViewModel()
        {
            RequestScopedCounter = 0;
            SessionScopedCounter = 0;
        }



        public void incrementCounters()
        {
            this.RequestScopedCounter++;
            this.SessionScopedCounter++;
        }
    }
}

Controllers/Demo01Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Is3106Lecture12DotNet.Models;
using Newtonsoft.Json;

namespace Is3106Lecture12DotNet.Controllers
{
    public class Demo01Controller : Controller
    {
        Demo01ViewModel demo01ViewModel;



        public Demo01Controller()
        {
            demo01ViewModel = new Demo01ViewModel();
        }



        public IActionResult Index()
        {
            return View();
        }



        public IActionResult IntegerCounter()
        {
            return View(demo01ViewModel);
        }



        [HttpPost]
        public IActionResult IntegerCounter(int _notUsed)
        {
            loadSessionIntegerCounter();
            demo01ViewModel.incrementCounters();
            updateSessionIntegerCounter();

            return View(demo01ViewModel);
        }



        public IActionResult StringAndObject()
        {
            loadSessionStringAndObjectInitial();
            return View(demo01ViewModel);
        }



        public IActionResult StringAndObjectRedirect()
        {
            loadSessionStringAndObjectRedirect();
            return View(demo01ViewModel);
        }



        private void loadSessionIntegerCounter()
        {
            int? sessionScopedCounter = HttpContext.Session.GetInt32("sessionScopedCounter");

            if (sessionScopedCounter == null)
            {
                sessionScopedCounter = 0;
                HttpContext.Session.SetInt32("sessionScopedCounter", 0);
            }

            demo01ViewModel.SessionScopedCounter = (int)sessionScopedCounter;
        }



        private void updateSessionIntegerCounter()
        {
            HttpContext.Session.SetInt32("sessionScopedCounter", demo01ViewModel.SessionScopedCounter);
        }



        private void loadSessionStringAndObjectInitial()
        {
            var sessionScopedString = HttpContext.Session.GetString("sessionScopedString");

            if (string.IsNullOrEmpty(sessionScopedString))
            {
                sessionScopedString = "Hello World! I am session scoped!";
                HttpContext.Session.SetString("sessionScopedString", sessionScopedString);
            }

            var sessionScopedObject = HttpContext.Session.GetString("sessionScopedObject");            

            if (string.IsNullOrEmpty(sessionScopedObject))
            {
                Book book = new Book(1, "978-8-01-111111-8", "Book 01", "Author 01");
                sessionScopedObject = JsonConvert.SerializeObject(book);
                HttpContext.Session.SetString("sessionScopedObject", sessionScopedObject);
            }

            demo01ViewModel.SessionScopedString = sessionScopedString;
            demo01ViewModel.SessionScopedObject = JsonConvert.DeserializeObject<Book>(sessionScopedObject);
        }



        private void loadSessionStringAndObjectRedirect()
        {
            // Don't need to check for null or empty value since we assume the respective session state already set
            var sessionScopedString = HttpContext.Session.GetString("sessionScopedString");            
            var sessionScopedObject = HttpContext.Session.GetString("sessionScopedObject");
        
            demo01ViewModel.SessionScopedString = sessionScopedString;
            demo01ViewModel.SessionScopedObject = JsonConvert.DeserializeObject<Book>(sessionScopedObject);
        }
    }
}

Views/Demo01/Index.cshtml
@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 1 - Session State ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo01 > Index</h2>

<h3>This is the Index view of Demo01Controller</h3>

Views/Demo01/IntegerCounter.cshtml
@model Is3106Lecture12DotNet.Models.Demo01ViewModel

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 1 - Session State - Integer Counter ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo01 > IntegerCounter</h2>

<form asp-action="IntegerCounter">
    <table>
        <tr>
            <th>
                Request Scoped Counter
            </th>
            <td>
                @Model.RequestScopedCounter
            </td>
        </tr>
        <tr>
            <th>
                Session Scoped Counter
            </th>
            <td>
                @Model.SessionScopedCounter
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Increment Counter" />
            </td>
        </tr>
    </table>
</form>

Views/Demo01/StringAndObject.cshtml
@model Is3106Lecture12DotNet.Models.Demo01ViewModel

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 1 - Session State - String and Object ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo01 > StringAndObject</h2>

<table>
    <tr>
        <th>
            Session Scoped String
        </th>
        <td>
            @Model.SessionScopedString
        </td>
    </tr>
    <tr>
        <th>
            Session Scoped Object
        </th>
        <td>
            <ul>
                <li>@Model.SessionScopedObject.ID</li>
                <li>@Model.SessionScopedObject.Isbn</li>
                <li>@Model.SessionScopedObject.Title</li>
                <li>@Model.SessionScopedObject.Author</li>
            </ul>            
        </td>
    </tr>
    <tr>
        <td colspan="2">
            @Html.ActionLink("Redirect", "StringAndObjectRedirect", "Demo01")
        </td>
    </tr>
</table>

Views/Demo01/StringAndObjectRedirect.cshtml
@model Is3106Lecture12DotNet.Models.Demo01ViewModel

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 1 - Session State - String and Object Redirect ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo01 > StringAndObjectRedirect</h2>

<table>
    <tr>
        <th>
            Session Scoped String
        </th>
        <td>
            @Model.SessionScopedString
        </td>
    </tr>
    <tr>
        <th>
            Session Scoped Object
        </th>
        <td>
            <ul>
                <li>@Model.SessionScopedObject.ID</li>
                <li>@Model.SessionScopedObject.Isbn</li>
                <li>@Model.SessionScopedObject.Title</li>
                <li>@Model.SessionScopedObject.Author</li>
            </ul>
        </td>
    </tr>
</table>