Models/Demo03ViewModel.cs
using ServiceReference1;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Is3106Lecture12DotNet.Models
{
    public class Demo03ViewModel
    {
        public book[] Books { get; set; }
        public book SelectedBookToView { get; set; }



        public Demo03ViewModel()
        {
        }
    }
}

Controllers/Demo03Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Threading.Tasks;
using Is3106Lecture12DotNet.Models;
using Microsoft.AspNetCore.Mvc;
using ServiceReference1;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Is3106Lecture12DotNet.Controllers
{
    public class Demo03Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult CreateBook()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> CreateBook([Bind("isbn,title,author")]book bk)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    BookWebServiceClient bookWebServiceClient = new BookWebServiceClient();
                    createBookReq req = new createBookReq();
                    req.book = bk;
                    createBookResponse response = await bookWebServiceClient.createBookAsync(req);
                    createBookRsp rsp = response.@return;

                    ViewData["InfoMessage"] = "New book created successfully: " + rsp.id;
                }
                catch(FaultException ex)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                }
            }
            else
            {
                ViewData["ErrorMessage"] = "Please correct the input data error and try again";
            }

            return View(bk);
        }




        public async Task<IActionResult> ViewAllBooks()
        {
            BookWebServiceClient bookWebServiceClient = new BookWebServiceClient();
            retrieveAllBooksResponse response = await bookWebServiceClient.retrieveAllBooksAsync();
            retrieveAllBooksRsp rsp = response.@return;

            Demo03ViewModel demo03ViewModel = new Demo03ViewModel();
            demo03ViewModel.Books = rsp.books;

            return View(demo03ViewModel);
        }



        public async Task<IActionResult> ViewBookDetails(int id)
        {
            BookWebServiceClient bookWebServiceClient = new BookWebServiceClient();
            retrieveBookResponse response = await bookWebServiceClient.retrieveBookAsync(id);
            retrieveBookRsp rsp = response.@return;

            Demo03ViewModel demo03ViewModel = new Demo03ViewModel();
            demo03ViewModel.SelectedBookToView = rsp.book;

            return View(demo03ViewModel);
        }



        public async Task<IActionResult> UpdateBook(int id)
        {
            BookWebServiceClient bookWebServiceClient = new BookWebServiceClient();
            retrieveBookResponse response = await bookWebServiceClient.retrieveBookAsync(id);
            retrieveBookRsp rsp = response.@return;

            return View(rsp.book);
        }



        [HttpPost]
        public async Task<IActionResult> UpdateBook([Bind("id,isbn,title,author")]book bk)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    BookWebServiceClient bookWebServiceClient = new BookWebServiceClient();
                    updateBookReq req = new updateBookReq();
                    req.book = bk;
                    req.book.idSpecified = true;
                    
                    updateBookResponse response = await bookWebServiceClient.updateBookAsync(req);

                    ViewData["InfoMessage"] = "Book updated successfully";
                }
                catch (FaultException ex)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                }
            }
            else
            {
                ViewData["ErrorMessage"] = "Please correct the input data error and try again";
            }            

            return View(bk);
        }



        public async Task<IActionResult> DeleteBook(int id)
        {
            BookWebServiceClient bookWebServiceClient = new BookWebServiceClient();
            deleteBookResponse response = await bookWebServiceClient.deleteBookAsync(id);

            return RedirectToAction("ViewAllBooks");
        }
    }    
}

Views/Demo03/CreateBook.cshtml
@model ServiceReference1.book

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 3 - SOAP Web Service - Create Book ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo03 > Create Book</h2>

<form asp-action="CreateBook">

    @if (ViewData["InfoMessage"] != null)
    {
        <div class="infoText">@ViewData["InfoMessage"]</div>
    }

    @if (ViewData["ErrorMessage"] != null)
    {
        <div class="errorText">@ViewData["ErrorMessage"]</div>
    }

    <table class="defaultTable" style="width: 100%;">        
        <tr>
            <th style="width: 200px;">
                ISBN
            </th>
            <td>
                <input asp-for="isbn" />
            </td>
            <td style="width: 400px;">
                <span asp-validation-for="isbn" class="errorText"></span>
            </td>
        </tr>
        <tr>
            <th style="width: 200px;">
                Title
            </th>
            <td>
                <input asp-for="title" />
            </td>
            <td style="width: 400px;">
                <span asp-validation-for="title" class="errorText"></span>
            </td>
        </tr>
        <tr>
            <th style="width: 200px;">
                Author
            </th>
            <td>
                <input asp-for="author" />
            </td>
            <td style="width: 400px;">
                <span asp-validation-for="author" class="errorText"></span>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <input type="submit" value="Create" class="btn btn-default" />
            </td>
        </tr>
    </table>
</form>

Views/Demo03/Index.cshtml
@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 3 - SOAP Web Service ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo03 > Index</h2>

<h3>This is the Index view of Demo03Controller</h3>

Views/Demo03/UpdateBook.cshtml
@model ServiceReference1.book

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 3 - SOAP Web Service - Update Book ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo03 > Update Book</h2>

<form asp-action="UpdateBook">

    @if (ViewData["InfoMessage"] != null)
    {
        <div class="infoText">@ViewData["InfoMessage"]</div>
    }

    @if (ViewData["ErrorMessage"] != null)
    {
        <div class="errorText">@ViewData["ErrorMessage"]</div>
    }

        <table class="defaultTable" style="width: 100%;">
            <tr>
                <th style="width: 200px;">
                    ID
                </th>
                <td>
                    @Model.id                    
                </td>
                <td style="width: 400px;">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <th style="width: 200px;">
                    ISBN
                </th>
                <td>
                    <input asp-for="isbn" />
                </td>
                <td style="width: 400px;">
                    <span asp-validation-for="isbn" class="errorText"></span>
                </td>
            </tr>
            <tr>
                <th style="width: 200px;">
                    Title
                </th>
                <td>
                    <input asp-for="title" />
                </td>
                <td style="width: 400px;">
                    <span asp-validation-for="title" class="errorText"></span>
                </td>
            </tr>
            <tr>
                <th style="width: 200px;">
                    Author
                </th>
                <td>
                    <input asp-for="author" />
                </td>
                <td style="width: 400px;">
                    <span asp-validation-for="author" class="errorText"></span>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <input type="submit" value="Update" class="btn btn-default" />
                </td>
            </tr>
        </table>
</form>

Views/Demo03/ViewAllBooks.cshtml
@model Is3106Lecture12DotNet.Models.Demo03ViewModel

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 3 - SOAP Web Service - View All Books ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo03 > ViewAllBooks</h2>

<table class="defaultTable" style="width: 100%;">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                ISBN
            </th>
            <th>
                Title
            </th>
            <th>
                Author
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model.Books)
        {
            <tr>
                <td>
                    @book.id
                </td>
                <td>
                    @book.isbn
                </td>
                <td>
                    @book.title
                </td>
                <td>
                    @book.author
                </td>
                <td>
                    @Html.ActionLink("View", "ViewBookDetails", "Demo03", new { id = book.id }) |
                    @Html.ActionLink("Update", "UpdateBook", "Demo03", new { id = book.id }) | 
                    @Html.ActionLink("Delete", "DeleteBook", "Demo03", new { id = book.id })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Demo03/ViewBookDetails.cshtml
@model Is3106Lecture12DotNet.Models.Demo03ViewModel

@{
    ViewData["Title"] = "*** IS3106 Lecture 12 DotNet :: 3 - SOAP Web Service - View Book Details ***";
}

<h1>@ViewData["Title"]</h1>
<h2>Demo03 > ViewBookDetails</h2>

<table class="defaultTable" style="width: 100%;">
    <tr>
        <th style="width: 200px;">
            ID
        </th>
        <td>
            @Model.SelectedBookToView.id
        </td>
    </tr>
    <tr>
        <th>
            ISBN
        </th>
        <td>
            @Model.SelectedBookToView.isbn
        </td>
    </tr>
    <tr>
        <th>
            Title
        </th>
        <td>
            @Model.SelectedBookToView.title
        </td>
    </tr>
    <tr>
        <th>
            Author
        </th>
        <td>
            @Model.SelectedBookToView.author
        </td>
    </tr>
</table>